/*
 * @Author: zhanghongqiao 
 * @Date: 2018-10-18 16:00:37 
 * @Email: 991034150@qq.com 
 * @Description: 我的收藏（全部）
 * @Last Modified by: zhanghongqiao
 * @Last Modified time: 2018-10-26 13:39:33
 */

export default {
  url: '/appletHome/getHomeMyCollectTab/:openId',
  // enableMock: true, // 是否使用本地假数据
  mock: {
    "erroCode":2000,
    "erroMsg":"",
    "result":[
      {
        "shared":0,
        "selfEq":1,
        "stationName":"25001",
        "equipmentId":"F009FA00E8",
        "stationId":"25001"
      },
      {
        "tvoc":"0.262",
        "iaqi":"131",
        "tvocLevel":"2",
        "temDesc":"舒适",
        "shared":1,
        "co2":"845",
        "co2Level":"3",
        "selfEq":0,
        "equipmentId":"F009FA012D",
        "hchoLevel":"3",
        "hcho":"0.034",
        "iaqiDesc":"净化",
        "pm25Level":"1",
        "pm25":"2",
        "stationName":"西北侧办公区",
        "iaqiLevel":"5",
        "humDesc":"舒适",
        "stationId":"17003"
      },
      {
        "tvoc":"0.304",
        "iaqi":"131",
        "tvocLevel":"2",
        "temDesc":"偏冷",
        "shared":1,
        "co2":"847",
        "co2Level":"3",
        "selfEq":0,
        "equipmentId":"F009FA011A",
        "hchoLevel":"3",
        "hcho":"0.034",
        "iaqiDesc":"净化",
        "pm25Level":"1",
        "pm25":"1",
        "stationName":"东北侧办公区",
        "iaqiLevel":"5",
        "humDesc":"舒适",
        "stationId":"17009"
      },
      {
        "shared":0,
        "selfEq":1,
        "stationName":"东北侧休息区",
        "equipmentId":"F009FA00F2",
        "stationId":"18002"
      },
      {
        "tvoc":"0.302",
        "iaqi":"130",
        "tvocLevel":"2",
        "temDesc":"舒适",
        "shared":1,
        "co2":"840",
        "co2Level":"3",
        "selfEq":1,
        "equipmentId":"F009FA00F8",
        "hchoLevel":"3",
        "hcho":"0.041",
        "iaqiDesc":"净化",
        "pm25Level":"1",
        "pm25":"2",
        "stationName":"西侧洽谈区",
        "iaqiLevel":"5",
        "humDesc":"舒适",
        "stationId":"17004"
      },
      {
        "tvoc":"0.316",
        "iaqi":"130",
        "tvocLevel":"2",
        "temDesc":"舒适",
        "shared":1,
        "co2":"836",
        "co2Level":"3",
        "selfEq":1,
        "equipmentId":"F009FA00F9",
        "hchoLevel":"3",
        "hcho":"0.045",
        "iaqiDesc":"净化",
        "pm25Level":"1",
        "pm25":"3",
        "stationName":"西南侧通道",
        "iaqiLevel":"5",
        "humDesc":"舒适",
        "stationId":"17005"
      },
      {
        "tvoc":"0.325",
        "iaqi":"126",
        "tvocLevel":"2",
        "temDesc":"舒适",
        "shared":1,
        "co2":"803",
        "co2Level":"3",
        "selfEq":1,
        "equipmentId":"F009FA00D8",
        "hchoLevel":"2",
        "hcho":"0.03",
        "iaqiDesc":"净化",
        "pm25Level":"1",
        "pm25":"1",
        "stationName":"东南侧办公区",
        "iaqiLevel":"5",
        "humDesc":"舒适",
        "stationId":"17007"
      },
      {
        "tvoc":"0.251",
        "iaqi":"126",
        "tvocLevel":"2",
        "temDesc":"偏冷",
        "shared":1,
        "co2":"805",
        "co2Level":"3",
        "selfEq":1,
        "equipmentId":"F009FA012E",
        "hchoLevel":"3",
        "hcho":"0.042",
        "iaqiDesc":"净化",
        "pm25Level":"1",
        "pm25":"1",
        "stationName":"南侧入口洽谈区",
        "iaqiLevel":"5",
        "humDesc":"舒适",
        "stationId":"17006"
      },
      {
        "shared":0,
        "selfEq":1,
        "stationName":"东侧办公区",
        "equipmentId":"F009FA0100",
        "stationId":"17008"
      },
      {
        "tvoc":"0.289",
        "iaqi":"124",
        "tvocLevel":"2",
        "temDesc":"偏冷",
        "shared":1,
        "co2":"785",
        "co2Level":"2",
        "selfEq":1,
        "equipmentId":"F009FA011E",
        "hchoLevel":"3",
        "hcho":"0.052",
        "iaqiDesc":"净化",
        "pm25Level":"1",
        "pm25":"1",
        "stationName":"北侧大会议室",
        "iaqiLevel":"5",
        "humDesc":"舒适",
        "stationId":"17001"
      },
      {
        "shared":0,
        "selfEq":1,
        "stationName":"北侧入口休息区",
        "equipmentId":"F009FA011C",
        "stationId":"17002"
      },
      {
        "tvoc":"0.332",
        "iaqi":"119",
        "tvocLevel":"2",
        "temDesc":"偏冷",
        "shared":1,
        "co2":"745",
        "co2Level":"2",
        "selfEq":1,
        "equipmentId":"F009FA011F",
        "hchoLevel":"3",
        "hcho":"0.041",
        "iaqiDesc":"适宜",
        "pm25Level":"1",
        "pm25":"2",
        "stationName":"北侧入口洽谈区",
        "iaqiLevel":"4",
        "humDesc":"舒适",
        "stationId":"18001"
      }
    ]
  }
}